apiVersion: v1
kind: ServiceAccount
metadata:
  name: quote-app-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "WORKLOAD_IDENTITY_CLIENT_ID"  # Will be updated by terraform
  labels:
    azure.workload.identity/use: "true"
